version: '3'

services:
# DB  ***************************************************************************************
  mongo:
    image: jbjares/mongo_java8_maven:v1
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/db.log
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    
    

    

    
    
    
    
    