version: '3'

services:
# SD  ***************************************************************************************
  servicediscovery: 
    image: jbjares/node-service-discovery:v10_dev
    ports:
    - 8881:8881
    links:
    - mongo
    depends_on:
    - mongo
    command: bash  -c "cd /app/trainmodellingtool-servicediscovery && mvn install -DskipTests && mvn spring-boot:run -Dserver.address=127.0.0.1 -Dserver.port=8881"
     

# DB  ***************************************************************************************
  mongo:
    image: jbjares/mongo_java8_maven:v1
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/db.log
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    
    

    

    
    
    
    
    