version: '3'

services:
# APP  ***************************************************************************************
  sd: 
    image: jbjares/train-model-service:v13 
    environment:
    - user_name=jbjares
    - server_port=8881
    - server_address=127.0.0.1
    - mongo_host=127.0.0.1
    - mongo_port=27018
    - app_env=dev
    - load_db=true
    ports:
    - 8881:8881
    links:
    - mongosd
    depends_on:
    - mongosd
    volumes:
     - "/Users/jbjares/workspaces/PHTWorkspace/central_workspace/pht-envsupport-servicelocator/mvnsteps-springboot-start.sh:/root/docker-entrypoint/mvnsteps-springboot-start.sh"
    command: bash -c "cd /app/ && chmod 777 -R /train-microservices-esb"
    command: bash -c "cd /root/docker-entrypoint/ && chmod +x mvnsteps-springboot-start.sh"
    command: bash -c "/root/docker-entrypoint/mvnsteps-springboot-start.sh"
    ##command: bash -c "cd /app/train-microservices-esb && mvn install -DskipTests && mvn spring-boot:run -Dserver.address=0.0.0.0 -Dserver.port=9091"

# DB  ***************************************************************************************
  mongosd:
    image: jbjares/mongo_java8_maven:v1
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/db.log
    volumes:
      - ./data/db:/data/db
    ports:
        - 27018:27018
    command: mongod --bind_ip_all --ipv6 --port $mongo_port --smallfiles --logpath=/dev/null # --quiet
    
    #docker run -d -p $mongo_port:$mongo_port jbjares/mongo_java8_maven:v1 mongod --bind_ip_all --ipv6 --port $mongo_port
