version: '3'

services:
# APP  ***************************************************************************************
  sd: 
    image: jbjares/train-platform-service-locator:${SD_TAG}
    environment:
    - user_name=$USERNAME
    - server_port=$SERVER_PORT
    - server_address=$SERVER_ADDRESS
    - mongo_host=$MONGO_HOST
    - mongo_port=$MONGO_PORT
    - app_env=$APP_ENV
    - load_db=$LOAD_DB
    ports:
    - $SERVER_PORT:8881
    links:
    - mongosd
    depends_on:
    - mongosd
    volumes:
     - "/app/service-locator-docker/:/app/service-locator-docker/"

    command: ["/app/service-locator-docker/wait-for-it.sh", "$MONGO_HOST:$MONGO_PORT","--timeout=60","--","/app/service-locator-docker/entrypoint.sh"]
    #command: bash -c "cd /app/service-locator-app/pht-envsupport-servicelocator && chmod 777 -R /app/service-locator-app/pht-envsupport-servicelocator"
    #command: bash -c "cd /app/service-locator-docker"
    #command: bash -c "/app/service-locator-docker/entrypoint.sh"
    ##command: bash -c "cd /app/train-microservices-esb && mvn install -DskipTests && mvn spring-boot:run -Dserver.address=0.0.0.0 -Dserver.port=9091"

# DB  ***************************************************************************************
  mongosd:
    image: jbjares/mongo_java8_maven:v1
    environment:
      - MONGO_DATA_DIR=/app/service-locator-data/db
      - MONGO_LOG_DIR=/app/service-locator-data/db.log
    volumes:
      - /app/service-locator-data/db:/app/service-locator-data/db
    ports:
        - $MONGO_PORT:27018
    command: --bind_ip_all --port $MONGO_PORT --ipv6 
    
    #docker run -d -p 27018:27018 jbjares/mongo_java8_maven:v1 mongod --bind_ip_all --ipv6 --port 28018
